name: Push MMFashion Model to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter your Replicate model name (e.g., your-username/aura-body-shape-analysis)'
        required: true

jobs:
  push_to_replicate:
    name: Push MMFashion to Replicate
    runs-on: ubuntu-latest
    
    # ==========================================================
    # THE DEFINITIVE FIX IS HERE
    # ==========================================================
    # This 'defaults' block sets the working directory for ALL subsequent 'run' steps in this job.
    defaults:
      run:
        working-directory: ./mmfashion 
        # Note: We assume the correct folder is 'mmfashion'. If the checkout creates a different name, adjust this.
    # ==========================================================

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          path: 'mmfashion' # We explicitly check out the code into a folder named 'mmfashion'

      - name: Setup Cog tool
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      # This step will now run inside the './mmfashion' directory
      - name: Download model weights from GCS
        run: |
          mkdir -p checkpoints
          wget -O checkpoints/epoch_100.pth "https://storage.googleapis.com/aura-world-class-models-300b/epoch_100.pth"

      # This step will ALSO run inside the './mmfashion' directory
      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}