name: Push MMFashion Model to Replicate (Timeout-Proof)

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter your Replicate model name (e.g., your-username/aura-body-shape-analysis)'
        required: true

jobs:
  push_to_replicate:
    name: Push MMFashion to Replicate
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Cog tool
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download model weights from GCS
        run: |
          mkdir -p checkpoints
          wget -O checkpoints/epoch_100.pth "https://storage.googleapis.com/aura-world-class-models-300b/epoch_100.pth"

      # ==========================================================
      # THE FIX: SPLIT BUILD AND PUSH
      # ==========================================================
      - name: Build Cog model image
        # The --push flag is removed. This step only builds the image locally on the runner.
        run: cog build -t r8.im/${{ inputs.model_name }}

      - name: Push model to Replicate
        # This step only pushes the already-built image. It's much faster.
        run: cog push r8.im/${{ inputs.model_name }}